### ISSUE TITLE
SomeLogicRando and SaveAnywhere bugs?

### ISSUE THREAD

**Issue by ahhh-reptar** [Denhonator/KHPCSpeedrunTools#11]
SaveAnyhwhere - Going to your Gummi Ship from Hollow Bastion sliding puzzle basement without undoing the puzzle will cause a softlock if you don't hit final button.  This is the only major bug listed here.

SomeLogicRando
- Kairi on Destiny Island (both versions of her) asks for weird items but seems to want original items
- Forget Me Nots are not required to progress to Mayor check in Halloween Town (still need to talk to Sally in graveyard, but what she gives doesn't seem to matter).
- Magic has missing letters or extra spaces depending on what was originally there and what you get now.
- Torn page in Dr. Finkelstein's bookcase is not randomized.
- Postcards in fan of Item Shop, Blue Safe in District 1, poster in Item Synthesis Workshop, and the two in the clock in the Gizmo Shop not randomized.  Rewards still are so not a big deal.
- Jiminy and Pinocchio are visible and on top of one another on the Watergleam Chest when you first enter Monstro.  You can still access this chest reasonably easily though.
- Leon had Dolphin Kick for beating him which could result in a soft lock if you both lose to him and have other copies of Dolphin Kick behind where one would be required through whatever reason.

I'm going to start another rando run and I'll update this thread if I find more stuff.

**Comment by ahhh-reptar** [comment]
SomeLogicRando
- Slides are not required in Deep Woods, only picking up whatever they've become.
- Ticket is not required to participate in Preliminaries in Olympus, only the cutscene.
- Donald gets intended magic at magic checks, not randomized magic.
- Gorilla gifts for clearing heartless in Deep Woods stalls if you finish fight with a summon out until summon fades.
- Gorilla gifts not randomized.
- Halloween Town doorbell elixir not randomized.  
- Bizarre Room book Mythril Shard not randomized.
- Postcard in Third District on balcony not randomized.
- Dalmatian rewards format weird (off center, uncolored, etc.)
- Junior Hero License not required to enter the games.

**Comment by Denhonator** [comment]
Thank you for the detailed report. However, these are practically all known and either intentional, can't reasonably be changed or just low priority.

Using SaveAnywhere to world map from anywhere is absolutely not safe. It can softlock and crash and cause other issues. It was intended more as a feature to escape softlocks etc. but people can't help not using it for their daily rando routing. Use it at your own responsibility.

The Kairi text bug is a result of swapping item data around. It could be coded around but as it is, it does actually serve as a way to find out what the rope and cloth are which is interesting and would be lost if the text was corrected.

Most key items aren't actually checked by the game; it instead checks story flags. This is why Jack-in-the-Box matters but Forget-Me-Not doesn't. With some work I could make all key items matter but that would be somewhat controversial since it could make progression too tedius. Still, it's something I would like to add as an option in future.

Magic upgrades have their text replaced in real-time. I could probably improve it but it's janky and scary since it can easily crash trying to put in more text than originally was in the text box.

Torn pages that aren't in chests are not randomized since it was causing some issues.

Postcards that aren't in chests are not randomized because items that aren't in chest or reward pool I can only reasonably randomize with per-item randomization, which would be quite problematic with postcards.

I don't know of a way to fix that bug when entering Monstro, but it's harmless.

Leon and Aerith checks which are missable are duplicated into chests, which the logic checks it they're available.

I haven't looked into how to randomize Donald's magic.

Only thing I could do to fix the powerwild fight fadeout when using summons would be to dismiss summon in script which I don't know how to do, but the bug is harmless and can be avoided.

Gummi rewards from Gorillas aren't in a reward pool I can manipulate.

Same with Halloween Town doorbell and many other random items that aren't in chest or reward pool.

First 3 Dalmatian rewards are normally gummi rewards (which would be useless) so they're replaced with reports 11-13. I have to use the real-time text replacement for it which again, is janky.

**Comment by Renzection** [comment]
I keep ending up with this error and dont know how to fix it.
![Capture](https://user-images.githubusercontent.com/40625563/140457867-393866c1-cdca-4430-8e58-ade1115e2294.PNG)
am i just not putting a file in the right location?

**Comment by Denhonator** [comment]
randofiles folder should be in the game installation folder, just like DINPUT8.dll. Or if you are using an older LuaBackend/LuaFrontend, same folder as the LuaBackend.exe

**Comment by Renzection** [comment]
Im using the LuaBackendDLL and i got it working now that its in the right location. Thank you :)
